In [23]:
import pandas as pd
import numpy as np
import os

# Caminho para o Excel original
xlsx_path = "../data/labels/OSATS.xlsx"

# Carregar o Excel
df = pd.read_excel(xlsx_path)

# Converter colunas relevantes para números (caso haja erros de tipo)
numeric_cols = [col for col in df.columns if 'OSATS_' in col or col.upper().startswith('GLOBA')]
df[numeric_cols] = df[numeric_cols].apply(pd.to_numeric, errors='coerce')

# Visualizar primeiras linhas
df.head()

,STUDENT,GROUP,TIME,SUTURES,INVESTIGATOR,VIDEO,OSATS_RESPECT,OSATS_MOTION,OSATS_INSTRUMENT,OSATS_SUTURE,OSATS_FLOW,OSATS_KNOWLEDGE,OSATS_PERFORMANCE,OSATS_FINAL_QUALITY,GLOBA_RATING_SCORE
0,AHO729,E-LEARNING,PRE,1.0,A,P54M,2,1,2,2,1,2,2,1,13
1,AHO729,E-LEARNING,PRE,1.0,B,P54M,2,1,3,1,2,1,2,1,13
2,AHO729,E-LEARNING,PRE,1.0,C,P54M,2,1,1,1,1,1,1,1,9
3,AHO729,E-LEARNING,POST,4.5,A,M45P,4,4,4,3,3,4,3,3,28
4,AHO729,E-LEARNING,POST,4.5,B,M45P,2,3,4,3,3,4,3,3,25

In [24]:
# Agrupar por vídeo e tirar média dos scores
df_grouped = df.groupby("VIDEO")[numeric_cols].mean().round(0).astype(int)

# Criar coluna GRS_CLASS (0 a 3)
def score_to_class(score):
    if score <= 15:
        return 0  # Novice
    elif score <= 23:
        return 1  # Intermediate
    elif score <= 31:
        return 2  # Proficient
    else:
        return 3  # Expert

df_grouped["GRS_CLASS"] = df_grouped["GLOBA_RATING_SCORE"].apply(score_to_class)

# Guardar CSV para Task 1
task1_df = df_grouped[["GRS_CLASS"]].reset_index()
task1_df.columns = ["VIDEO", "GRS"]
task1_df.to_csv("../data/labels/labels_task1.csv", index=False)
print("✅ CSV da Task 1 guardado.")
task1_df.head()

✅ CSV da Task 1 guardado.

  VIDEO  GRS
0  A31H    0
1  A36O    0
2  A40E    1
3  A41X    3
4  A59Z    0

In [25]:
# Extrair colunas OSATS
osats_cols = [col for col in df_grouped.columns if col.startswith("OSATS_")]
task2_df = df_grouped[osats_cols].reset_index()

# Ordenar colunas conforme o output requerido
ordered_cols = [
    "VIDEO",
    "OSATS_RESPECT",
    "OSATS_MOTION",
    "OSATS_INSTRUMENT",
    "OSATS_SUTURE",
    "OSATS_FLOW",
    "OSATS_KNOWLEDGE",
    "OSATS_PERFORMANCE",
    "OSATS_FINAL_QUALITY"
]
task2_df = task2_df[ordered_cols]
task2_df.to_csv("../data/labels/labels_task2.csv", index=False)
print("✅ CSV da Task 2 guardado.")
task2_df.head()

✅ CSV da Task 2 guardado.

,VIDEO,OSATS_RESPECT,OSATS_MOTION,OSATS_INSTRUMENT,OSATS_SUTURE,OSATS_FLOW,OSATS_KNOWLEDGE,OSATS_PERFORMANCE,OSATS_FINAL_QUALITY
0,A31H,1,2,2,2,2,2,2,1
1,A36O,3,1,2,1,1,1,1,1
2,A40E,3,2,2,2,2,2,2,2
3,A41X,5,4,4,5,4,4,4,4
4,A59Z,2,1,2,1,1,1,1,1